"""Extend Conversation and Message models to support async behaviour.

Revision ID: e8e179abf791
Revises: 7485721da8b9
Create Date: 2025-11-20 10:41:19.910018+00:00

"""

from __future__ import annotations

import warnings

import sqlalchemy as sa
from alembic import op


__all__ = ["downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades"]

# revision identifiers, used by Alembic.
revision = "e8e179abf791"
down_revision = "7485721da8b9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)

        schema_upgrades()
        data_upgrades()
        schema_upgrades_pos_data()


def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)

        data_downgrades()
        schema_downgrades()


def schema_upgrades() -> None:
    """Schema upgrade migrations go here."""

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("message", schema=None) as batch_op:
        batch_op.add_column(sa.Column("status", sa.String(), nullable=False))
        batch_op.add_column(sa.Column("metadata_", sa.JSON(), nullable=True))

    with op.batch_alter_table("plugin", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_plugin_organization_id_organization"), type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_plugin_organization_id_organization"), "organization", ["organization_id"], ["id"]
        )

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column("firebase_id", existing_type=sa.VARCHAR(), nullable=False)

    # ### end Alembic commands ###


def schema_downgrades() -> None:
    """Schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column("firebase_id", existing_type=sa.VARCHAR(), nullable=True)

    with op.batch_alter_table("plugin", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_plugin_organization_id_organization"), type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_plugin_organization_id_organization"),
            "organization",
            ["organization_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("message", schema=None) as batch_op:
        batch_op.drop_column("metadata_")
        batch_op.drop_column("status")

    # ### end Alembic commands ###


def schema_upgrades_pos_data() -> None:
    """Schema upgrade migrations that need to be run after data migrations go here."""


def data_upgrades() -> None:
    """Data upgrade migrations go here."""


def data_downgrades() -> None:
    """Data downgrade migrations go here."""
