"""Adjusting Document Content To Account For Multiple Sections.

Revision ID: f8bd14d8521d
Revises: ca9673d3a6bd
Create Date: 2025-11-17 16:36:51.091231+00:00

"""

from __future__ import annotations

import warnings

import sqlalchemy as sa
import sqlmodel
from alembic import op


__all__ = ["downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades"]

# revision identifiers, used by Alembic.
revision = "f8bd14d8521d"
down_revision = "ca9673d3a6bd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)

        schema_upgrades()
        data_upgrades()
        schema_upgrades_pos_data()


def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)

        data_downgrades()
        schema_downgrades()


def schema_upgrades() -> None:
    """Schema upgrade migrations go here."""

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("document_content", schema=None) as batch_op:
        batch_op.add_column(sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column("order_index", sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f("uq_document_content_document_id"), type_="unique")

    # ### end Alembic commands ###


def schema_downgrades() -> None:
    """Schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("document_content", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            batch_op.f("uq_document_content_document_id"), ["document_id"], postgresql_nulls_not_distinct=False
        )
        batch_op.drop_column("order_index")
        batch_op.drop_column("title")

    # ### end Alembic commands ###


def schema_upgrades_pos_data() -> None:
    """Schema upgrade migrations that need to be run after data migrations go here."""


def data_upgrades() -> None:
    """Data upgrade migrations go here."""


def data_downgrades() -> None:
    """Data downgrade migrations go here."""
