"""Enable emmbedded content in documents.

Revision ID: ca818909d8fc
Revises: 7f6a0a5fb5c9
Create Date: 2025-11-24 03:18:53.888418+00:00

"""

from __future__ import annotations

import warnings

import sqlalchemy as sa
from alembic import op


__all__ = ["downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades"]

# revision identifiers, used by Alembic.
revision = "ca818909d8fc"
down_revision = "7f6a0a5fb5c9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)

        schema_upgrades()
        data_upgrades()
        schema_upgrades_pos_data()


def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)

        data_downgrades()
        schema_downgrades()


def schema_upgrades() -> None:
    """Schema upgrade migrations go here."""

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("document_content", schema=None) as batch_op:
        batch_op.add_column(sa.Column("embedded_content_id", sa.BigInteger(), nullable=True))
        batch_op.create_foreign_key(
            batch_op.f("fk_document_content_embedded_content_id_content"),
            "content",
            ["embedded_content_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###


def schema_downgrades() -> None:
    """Schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("document_content", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_document_content_embedded_content_id_content"), type_="foreignkey")
        batch_op.drop_column("embedded_content_id")

    # ### end Alembic commands ###


def schema_upgrades_pos_data() -> None:
    """Schema upgrade migrations that need to be run after data migrations go here."""


def data_upgrades() -> None:
    """Data upgrade migrations go here."""


def data_downgrades() -> None:
    """Data downgrade migrations go here."""
