"""add ciim geo image url to earthquake model.

Revision ID: 19e4ee3e3cb7
Revises: e2657a6d6947
Create Date: 2025-10-19 18:31:04.808453+00:00

"""

from __future__ import annotations

import warnings

import sqlalchemy as sa
from alembic import op


__all__ = ["downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades"]

# revision identifiers, used by Alembic.
revision = "19e4ee3e3cb7"
down_revision = "e2657a6d6947"
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)

        schema_upgrades()
        data_upgrades()
        schema_upgrades_pos_data()


def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)

        data_downgrades()
        schema_downgrades()


def schema_upgrades() -> None:
    """Schema upgrade migrations go here."""

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("earthquake", schema=None) as batch_op:
        batch_op.add_column(sa.Column("ciim_geo_image_url", sa.String(length=1024), nullable=True))

    # ### end Alembic commands ###


def schema_downgrades() -> None:
    """Schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("earthquake", schema=None) as batch_op:
        batch_op.drop_column("ciim_geo_image_url")

    # ### end Alembic commands ###


def schema_upgrades_pos_data() -> None:
    """Schema upgrade migrations that need to be run after data migrations go here."""


def data_upgrades() -> None:
    """Data upgrade migrations go here."""


def data_downgrades() -> None:
    """Data downgrade migrations go here."""
