export const env = {
  NEXT_PUBLIC_API_URL: process.env.NEXT_PUBLIC_API_URL,
  NEXT_PUBLIC_FIREBASE_API_KEY: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
  NEXT_PUBLIC_FIREBASE_PROJECT_ID: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
  NEXT_PUBLIC_USE_MOCKS: process.env.NEXT_PUBLIC_USE_MOCKS === "true",
  NEXT_PUBLIC_SKIP_AUTH: process.env.NEXT_PUBLIC_SKIP_AUTH === "true",
  NEXT_PUBLIC_X_OAUTH_CLIENT_ID: process.env.NEXT_PUBLIC_X_OAUTH_CLIENT_ID,
  NEXT_PUBLIC_X_OAUTH_REDIRECT_URI: process.env.NEXT_PUBLIC_X_OAUTH_REDIRECT_URI,
  NEXT_PUBLIC_X_OAUTH_SCOPES: process.env.NEXT_PUBLIC_X_OAUTH_SCOPES,
  NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,

}
export type Env = typeof env
